<stat><activeclients>0</activeclients>
<hits>0</hits>
<records>0</records>
<clients>0</clients>
<unconnected>0</unconnected>
<connecting>0</connecting>
<working>0</working>
<idle>0</idle>
<failed>0</failed>
<error>0</error>
<progress>0.00</progress>
</stat>