language: c
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env:
       - MY_OS=trusty
    - os: linux
      dist: precise
      compiler: gcc
      env:
       - MY_OS=precise
    - os: osx
      osx_image: beta-xcode6.1
      env:
       - MY_OS=macos-10.9
    - os: osx
      osx_image: xcode7
      env:
       - MY_OS=macos-10.10
    - os: osx
      osx_image: xcode7.3
      env:
       - MY_OS=macos-10.11
    - os: osx
      osx_image: xcode8
      env:
       - MY_OS=macos-10.11

addons:
 apt:
  packages:
   - autoconf
   - autotools-dev
   - automake
   - bison
   - docbook
   - docbook-xml
   - docbook-xsl
   - gcc
   - libgnutls-dev
   - libhiredis-dev
   - libicu-dev
   - libmemcached-dev
   - libreadline-dev
   - libtool
   - libwrap0-dev
   - libxslt1-dev
   - make
   - pkg-config
   - tcl8.5
   - xsltproc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install icu4c yaz docbook-xsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then XML_CATALOG_FILES=/usr/local/etc/xml/catalog; export XML_CATALOG_FILES; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/travis/travis-init.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -yq libyaz5-dev; fi

before_script:
 - ./buildconf.sh

script:
 - ./configure
 - make -j3
 - make check

