Document: pazpar2
Title: Debian pazpar2 Manual
Author: <insert document author here>
Abstract: This manual describes what pazpar2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pazpar2/pazpar2.sgml.gz

Format: postscript
Files: /usr/share/doc/pazpar2/pazpar2.ps.gz

Format: text
Files: /usr/share/doc/pazpar2/pazpar2.text.gz

Format: HTML
Index: /usr/share/doc/pazpar2/html/index.html
Files: /usr/share/doc/pazpar2/html/*.html

  
